### ISSUE TITLE
Add timeline bar for hours

### ISSUE THREAD

**Issue by Shirokone** [habiteam/habitea#34]
Add bar to timeline that shows actual hour

**Comment by nzawirski** [comment]
@Shirokone Take a look and close issue if this is good enough.
![Screenshot from 2023-02-11 21-47-13](https://user-images.githubusercontent.com/43851876/218280843-d5104f94-0241-41cc-b825-ef4bfd7e2ecc.png)

**Comment by Shirokone** [comment]
When i created issue i found perfect example:

![image](https://user-images.githubusercontent.com/43843598/218282413-a5dc3b41-8cac-4c2b-9468-6bb72c5ef692.png)

**Comment by Shirokone** [comment]
so yeah half way there 👍

**Comment by nzawirski** [comment]
@Shirokone Current time display added. [Previewable here](https://deploy-preview-39--habitea.netlify.app/)

**Comment by nzawirski** [comment]
Pushed live in 1.0.2 (#39 ). Closing.
